name: .NET 9 Web App Build, Publish & Runtime Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: sapassword
          MYSQL_DATABASE: CRM
          MYSQL_USER: sa
          MYSQL_PASSWORD: sapassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u sa -psapassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SOLUTION_FILE: CRM.sln
      PROJECT_FILE: CRM/CRM.csproj
      TEST_ENDPOINT: /api/Data/GetVersionInfo
      POSSIBLE_PORTS: "5201 7048 15497"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Wait for MySQL service to be ready
      run: |
        echo "Waiting for MySQL to accept connections..."
        for i in {1..30}; do
          if mysql -h 127.0.0.1 -P 3306 -u sa -psapassword -e "SELECT 1;" crmdb; then
            echo "✅ MySQL is ready"
            break
          fi
          echo "⏳ Waiting ($i)..."
          sleep 2
        done

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build solution (${{ matrix.configuration }})
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Publish project (${{ matrix.configuration }})
      run: dotnet publish ${{ env.PROJECT_FILE }} --configuration ${{ matrix.configuration }} --no-build --output ./publish/${{ matrix.configuration }}

    - name: Upload published artifact (${{ matrix.configuration }})
      uses: actions/upload-artifact@v4
      with:
        name: WebApp-${{ matrix.configuration }}
        path: ./publish/${{ matrix.configuration }}

    - name: Run runtime smoke test (${{ matrix.configuration }})
      shell: bash
      run: |
        echo "Starting app in background with logs..."
        dotnet ./publish/${{ matrix.configuration }}/$(basename ${{ env.PROJECT_FILE }} .csproj).dll &
        APP_PID=$!

        timeout=60
        elapsed=0
        success=0

        echo "Trying ports: ${{ env.POSSIBLE_PORTS }}"
        while [ $elapsed -lt $timeout ]; do
          for port in ${{ env.POSSIBLE_PORTS }}; do
            url="http://localhost:$port${{ env.TEST_ENDPOINT }}"
            echo "Checking $url ..."
            response=$(curl -s -w "%{http_code}" -o response.json $url || true)
            if [ "$response" = "200" ]; then
              echo "✅ App responded at $url"
              echo "Response body:"
              cat response.json
              success=1
              break 2
            fi
          done
          sleep 2
          elapsed=$((elapsed+2))
        done

        if [ $success -eq 0 ]; then
          echo "❌ App failed to respond on any of the candidate ports within $timeout seconds"
          kill $APP_PID || true
          exit 1
        fi

        kill $APP_PID || true
